### PR TITLE
feat: Add deprecated shape remover

### PR DESCRIPTION
**Pull request by sichanyoo**
## Issue \#

https://github.com/awslabs/aws-sdk-swift/issues/1026

## Description of changes

- Adds model preprocessing that removes shapes with deprecated trait based on `since` property if earlier than cutoff date.

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jbelkins — COMMENTED** [review]
The code looks good.

My larger question is whether this logic can lead to breakage where something that depends on a deprecated & removed shape will break (i.e. what if there is a member shape that targets a shape deprecated before our GA.)  Not sure if Smithy validates these deprecation traits to make sure that things that depend on deprecated shapes are themselves deprecated.

If it's indeed the case that Smithy validates against that or otherwise protects against this scenario, I'll approve.

**Review by jbelkins — CHANGES_REQUESTED** [review]
Something that just occurred to me on this:

This belongs in SDK, not smithy-swift.

Move this over to aws-sdk-swift and I will re-review.

**Comment by sichanyoo** [comment]
@jbelkins 

Smithy does protect against that. Using `ModelTransformer::removeShapesIf` ensures the model is left in consistent state after removal (any reference to removed shape is removed as well).

Re: this change being appropriate for SDK side, that's a great catch. I'll move changes there and submit PR soon.

**Comment by sichanyoo** [comment]
Remover change moved to aws-sdk-swift: https://github.com/awslabs/aws-sdk-swift/pull/1511

**Pull request closed without merging**
